using System.Collections.Generic;
using DomurTech.ERP.Data.Entities.Concrete;

namespace DomurTech.Installation.Common.DefaultDatas
{
    internal class CityDatas
    {
        public List<CityLanguageLine> CityLanguageLines = new List<CityLanguageLine>
        {
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-01"}, CityName = "Adana"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-02"}, CityName = "Adýyaman"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-03"}, CityName = "Afyonkarahisar"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-04"}, CityName = "Aðrý"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-05"}, CityName = "Amasya"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-06"}, CityName = "Ankara"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-07"}, CityName = "Antalya"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-08"}, CityName = "Artvin"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-09"}, CityName = "Aydýn"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-10"}, CityName = "Balýkesir"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-11"}, CityName = "Bilecik"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-12"}, CityName = "Bingöl"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-13"}, CityName = "Bitlis"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-14"}, CityName = "Bolu"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-15"}, CityName = "Burdur"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-16"}, CityName = "Bursa"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-17"}, CityName = "Çanakkale"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-18"}, CityName = "Çankýrý"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-19"}, CityName = "Çorum"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-20"}, CityName = "Denizli"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-21"}, CityName = "Diyarbakýr"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-22"}, CityName = "Edirne"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-23"}, CityName = "Elazýð"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-24"}, CityName = "Erzincan"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-25"}, CityName = "Erzurum"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-26"}, CityName = "Eskiþehir"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-27"}, CityName = "Gaziantep"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-28"}, CityName = "Giresun"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-29"}, CityName = "Gümüþhane"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-30"}, CityName = "Hakkari"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-31"}, CityName = "Hatay"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-32"}, CityName = "Isparta"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-33"}, CityName = "Mersin"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-34"}, CityName = "Ýstanbul"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-35"}, CityName = "Ýzmir"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-36"}, CityName = "Kars"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-37"}, CityName = "Kastamonu"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-38"}, CityName = "Kayseri"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-39"}, CityName = "Kýrklareli"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-40"}, CityName = "Kýrþehir"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-41"}, CityName = "Kocaeli"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-42"}, CityName = "Konya"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-43"}, CityName = "Kütahya"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-44"}, CityName = "Malatya"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-45"}, CityName = "Manisa"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-46"}, CityName = "Kahramanmaraþ"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-47"}, CityName = "Mardin"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-48"}, CityName = "Muðla"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-49"}, CityName = "Muþ"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-50"}, CityName = "Nevþehir"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-51"}, CityName = "Niðde"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-52"}, CityName = "Ordu"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-53"}, CityName = "Rize"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-54"}, CityName = "Sakarya"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-55"}, CityName = "Samsun"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-56"}, CityName = "Siirt"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-57"}, CityName = "Sinop"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-58"}, CityName = "Sivas"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-59"}, CityName = "Tekirdað"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-60"}, CityName = "Tokat"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-61"}, CityName = "Trabzon"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-62"}, CityName = "Tunceli"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-63"}, CityName = "Þanlýurfa"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-64"}, CityName = "Uþak"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-65"}, CityName = "Van"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-66"}, CityName = "Yozgat"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-67"}, CityName = "Zonguldak"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-68"}, CityName = "Aksaray"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-69"}, CityName = "Bayburt"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-70"}, CityName = "Karaman"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-71"}, CityName = "Kýrýkkale"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-72"}, CityName = "Batman"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-73"}, CityName = "Þýrnak"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-74"}, CityName = "Bartýn"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-75"}, CityName = "Ardahan"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-76"}, CityName = "Iðdýr"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-77"}, CityName = "Yalova"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-78"}, CityName = "Karabük"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-79"}, CityName = "Kilis"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-80"}, CityName = "Osmaniye"},
            new CityLanguageLine {City = new City {Country = new Country {CountryCode = "TUR"}, CityCode = "TR-81"}, CityName = "Düzce"}
        };
    }
}