//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomurTech.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomurTech.Globalization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm hakları saklıdır..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt tekrar edilmiş!.
        /// </summary>
        public static string DangerDuplicatedRecord {
            get {
                return ResourceManager.GetString("DangerDuplicatedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} daha önce kullanılmış!.
        /// </summary>
        public static string DangerFieldDuplicated {
            get {
                return ResourceManager.GetString("DangerFieldDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı boş!.
        /// </summary>
        public static string DangerFieldIsEmpty {
            get {
                return ResourceManager.GetString("DangerFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı {1} karakterden az girilmiş!.
        /// </summary>
        public static string DangerFieldLengthLimit {
            get {
                return ResourceManager.GetString("DangerFieldLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanları uyuşmuyor!.
        /// </summary>
        public static string DangerFiledsDoNotMatch {
            get {
                return ResourceManager.GetString("DangerFiledsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut şifre hatalı!.
        /// </summary>
        public static string DangerIncorrectOldPassword {
            get {
                return ResourceManager.GetString("DangerIncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı şifre!.
        /// </summary>
        public static string DangerIncorrectPassword {
            get {
                return ResourceManager.GetString("DangerIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı kullanıcı adı!.
        /// </summary>
        public static string DangerIncorrectUsername {
            get {
                return ResourceManager.GetString("DangerIncorrectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı Kullanıcı adı veya şifre!.
        /// </summary>
        public static string DangerIncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("DangerIncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik geçerli değil!.
        /// </summary>
        public static string DangerInvalidEntitiy {
            get {
                return ResourceManager.GetString("DangerInvalidEntitiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yeterince karmaşık değil!.
        /// </summary>
        public static string DangerInvalidPassword {
            get {
                return ResourceManager.GetString("DangerInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} daha önce kullanılmış!.
        /// </summary>
        public static string DangerItemDuplicated {
            get {
                return ResourceManager.GetString("DangerItemDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} boş!.
        /// </summary>
        public static string DangerItemIsEmpty {
            get {
                return ResourceManager.GetString("DangerItemIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1} karakterden az girilmiş!.
        /// </summary>
        public static string DangerItemLengthLimit {
            get {
                return ResourceManager.GetString("DangerItemLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgili kayıt onaylı değil!.
        /// </summary>
        public static string DangerItemNotApproved {
            get {
                return ResourceManager.GetString("DangerItemNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlem için yetkiniz yok!.
        /// </summary>
        public static string DangerNoPermission {
            get {
                return ResourceManager.GetString("DangerNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreler aynı değil!.
        /// </summary>
        public static string DangerPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("DangerPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı!.
        /// </summary>
        public static string DangerRecordNotFound {
            get {
                return ResourceManager.GetString("DangerRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik kodu uyuşmuyor!.
        /// </summary>
        public static string DangerSecurityCodesDoNotMatched {
            get {
                return ResourceManager.GetString("DangerSecurityCodesDoNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bilgisi başarıyla güncellendi..
        /// </summary>
        public static string InfoAccountInformationUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("InfoAccountInformationUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleme işlemi başarısızlıkla sonuçlandı..
        /// </summary>
        public static string InfoAddOperationNotSuccessful {
            get {
                return ResourceManager.GetString("InfoAddOperationNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleme İşlemi Başarılı..
        /// </summary>
        public static string InfoAddOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoAddOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adet kayıt silindi..
        /// </summary>
        public static string InfoDeletedRecordCount {
            get {
                return ResourceManager.GetString("InfoDeletedRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme işlemi başarısızlıkla sonuçlandı!.
        /// </summary>
        public static string InfoDeletionOperationNotSuccessful {
            get {
                return ResourceManager.GetString("InfoDeletionOperationNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme işlemi başarıyla tamamlandı..
        /// </summary>
        public static string InfoDeletionOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoDeletionOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı başarıyla güncellenemedi!.
        /// </summary>
        public static string InfoFieldUpdatedNotSuccesfully {
            get {
                return ResourceManager.GetString("InfoFieldUpdatedNotSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı başarıyla güncellendi..
        /// </summary>
        public static string InfoFieldUpdatedSuccesfully {
            get {
                return ResourceManager.GetString("InfoFieldUpdatedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla giriş yapıldı..
        /// </summary>
        public static string InfoLoginOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoLoginOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla çıkış yapıldı..
        /// </summary>
        public static string InfoLogoutOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoLogoutOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı!.
        /// </summary>
        public static string InfoNoRecordsFound {
            get {
                return ResourceManager.GetString("InfoNoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başrasızlıkla sonuçlandı!.
        /// </summary>
        public static string InfoOperationNotSuccessful {
            get {
                return ResourceManager.GetString("InfoOperationNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarıyla sonuçlandı..
        /// </summary>
        public static string InfoOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre başarıyla gönderildi..
        /// </summary>
        public static string InfoPasswordSentSuccesfully {
            get {
                return ResourceManager.GetString("InfoPasswordSentSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydetme işlemi başarısızlıkla sonuçlandı!.
        /// </summary>
        public static string InfoSaveOperationNotSuccessful {
            get {
                return ResourceManager.GetString("InfoSaveOperationNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydetme işlemi başarıyla tamamlandı..
        /// </summary>
        public static string InfoSaveOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoSaveOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenleme işlemi başarılı..
        /// </summary>
        public static string InfoUpdateOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoUpdateOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSure {
            get {
                return ResourceManager.GetString("QuestionAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilenleri onaylamak istediğinizden emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSureApproveSelected {
            get {
                return ResourceManager.GetString("QuestionAreYouSureApproveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSureDelete {
            get {
                return ResourceManager.GetString("QuestionAreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili olanları silmek istediinizden emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSureDeleteSelected {
            get {
                return ResourceManager.GetString("QuestionAreYouSureDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralamayı keydetmek istediğinizden emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSureForSorting {
            get {
                return ResourceManager.GetString("QuestionAreYouSureForSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumu sonlandırmak istediğinizden emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSureLogout {
            get {
                return ResourceManager.GetString("QuestionAreYouSureLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen {0} alanını kontrol ediniz!.
        /// </summary>
        public static string WarnCheckField {
            get {
                return ResourceManager.GetString("WarnCheckField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen kullanıcı adı ve şifrenizi kontrol ediniz!.
        /// </summary>
        public static string WarnCheckUsernameAndPassword {
            get {
                return ResourceManager.GetString("WarnCheckUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen site yöneticinizle görüşünüz!.
        /// </summary>
        public static string WarnContactYourSiteAdmin {
            get {
                return ResourceManager.GetString("WarnContactYourSiteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı boş olamaz!.
        /// </summary>
        public static string WarnFieldCannotBeEmpty {
            get {
                return ResourceManager.GetString("WarnFieldCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} en az {1} karakter olmalıdır!.
        /// </summary>
        public static string WarnFieldLength {
            get {
                return ResourceManager.GetString("WarnFieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanına geçerli veri giriniz!.
        /// </summary>
        public static string WarnInvalidField {
            get {
                return ResourceManager.GetString("WarnInvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} boş olamaz!.
        /// </summary>
        public static string WarnItemCannotBeEmpty {
            get {
                return ResourceManager.GetString("WarnItemCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapmalı ya da kayıt olmalısınız!.
        /// </summary>
        public static string WarnLoginOrRegister {
            get {
                return ResourceManager.GetString("WarnLoginOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum süresi doldu!.
        /// </summary>
        public static string WarnSessionTimeOut {
            get {
                return ResourceManager.GetString("WarnSessionTimeOut", resourceCulture);
            }
        }
    }
}
